// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmO-f9u72NBAqTGZB0j8DOKbEOkd4NTNw',
    appId: '1:826670634020:web:81f888fd755494a70534b1',
    messagingSenderId: '826670634020',
    projectId: 'officesports-5d7ac',
    authDomain: 'officesports-5d7ac.firebaseapp.com',
    storageBucket: 'officesports-5d7ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCmNGbfBdHNI-0uZDnjFyUGzhpokG7JsE',
    appId: '1:826670634020:android:0f02f68b122a7c1d0534b1',
    messagingSenderId: '826670634020',
    projectId: 'officesports-5d7ac',
    storageBucket: 'officesports-5d7ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZaD6RUmvho85pZQPRGoX86Q40cCEGEhI',
    appId: '1:826670634020:ios:91eca6189c99303a0534b1',
    messagingSenderId: '826670634020',
    projectId: 'officesports-5d7ac',
    storageBucket: 'officesports-5d7ac.appspot.com',
    androidClientId: '826670634020-441rvgqit74n7kiql0otdt64kfihf3ji.apps.googleusercontent.com',
    iosClientId: '826670634020-ustau3fb1ghujn57imnokmph8vqig30m.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeSportsAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZaD6RUmvho85pZQPRGoX86Q40cCEGEhI',
    appId: '1:826670634020:ios:91eca6189c99303a0534b1',
    messagingSenderId: '826670634020',
    projectId: 'officesports-5d7ac',
    storageBucket: 'officesports-5d7ac.appspot.com',
    androidClientId: '826670634020-441rvgqit74n7kiql0otdt64kfihf3ji.apps.googleusercontent.com',
    iosClientId: '826670634020-ustau3fb1ghujn57imnokmph8vqig30m.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeSportsAndroid',
  );
}
